# Warm-up round: Steady-state flux distributions

$$
find \quad v \\
s.t. \quad 
Sv = 0 \\
\quad\quad l \leq v \leq u
$$

In [1]:
using SparseArrays
using JuMP
using GLPK

In [2]:
s= open("R2T2.txt") do file
   read(file, String)
end
print(s)

matrix,row,col
S,8404,13094
I,J,V
1962.0,1.0,1.0
3086.0,1.0,-1.0
3518.0,1.0,1.0
4360.0,1.0,-1.0
4366.0,1.0,1.0
1962.0,2.0,1.0
3086.0,2.0,-1.0
3518.0,2.0,1.0
4371.0,2.0,-1.0
4378.0,2.0,1.0
1970.0,3.0,-1.0
1992.0,3.0,1.0
2122.0,3.0,1.0
2210.0,3.0,-1.0
2642.0,3.0,-1.0
4768.0,3.0,1.0
1972.0,4.0,-1.0
1994.0,4.0,1.0
2125.0,4.0,1.0
2213.0,4.0,-1.0
2645.0,4.0,-1.0
4769.0,4.0,1.0
1986.0,5.0,-1.0
1992.0,5.0,1.0
2122.0,5.0,1.0
2642.0,5.0,-1.0
3518.0,5.0,1.0
1970.0,6.0,-1.0
1986.0,6.0,1.0
2210.0,6.0,-1.0
3518.0,6.0,-1.0
4768.0,6.0,1.0
1994.0,7.0,1.0
2638.0,7.0,1.0
2645.0,7.0,-1.0
4361.0,7.0,-1.0
4367.0,7.0,1.0
4890.0,7.0,-1.0
3523.0,8.0,-1.0
4112.0,8.0,1.0
4363.0,8.0,1.0
4368.0,8.0,-1.0
4891.0,8.0,-1.0
3518.0,9.0,-1.0
4110.0,9.0,1.0
4360.0,9.0,1.0
4366.0,9.0,-1.0
4889.0,9.0,-1.0
1962.0,10.0,-1.0
1970.0,10.0,1.0
3518.0,10.0,2.0
3526.0,10.0,-1.0
4371.0,10.0,-1.0
4378.0,10.0,1.0
1963.0,11.0,-1.0
1972.0,11.0,1.0
3521.0,11.0,2.0
3529.0,11.0,-1.0
4361.0,11.0,-1.0
4367.0,11.0,1.0
2032.0,12.0,1.0
2210.0,1

5390.0,1296.0,5.0
5471.0,1296.0,7.0
2032.0,1297.0,98.0
2076.0,1297.0,15.0
2167.0,1297.0,-1.0
2194.0,1297.0,4.0
2206.0,1297.0,7.0
2210.0,1297.0,-98.0
3374.0,1297.0,5.0
3379.0,1297.0,6.0
3399.0,1297.0,3.0
3518.0,1297.0,100.0
3526.0,1297.0,-196.0
3683.0,1297.0,1.0
4017.0,1297.0,11.0
4147.0,1297.0,6.0
4236.0,1297.0,3.0
4698.0,1297.0,4.0
4748.0,1297.0,98.0
4789.0,1297.0,3.0
4999.0,1297.0,12.0
5211.0,1297.0,5.0
5368.0,1297.0,3.0
5390.0,1297.0,2.0
5471.0,1297.0,9.0
2032.0,1298.0,2673.0
2076.0,1298.0,134.0
2194.0,1298.0,134.0
2202.0,1298.0,138.0
2206.0,1298.0,176.0
2210.0,1298.0,-2673.0
2707.0,1298.0,48.0
3137.0,1298.0,-1.0
3374.0,1298.0,186.0
3379.0,1298.0,110.0
3399.0,1298.0,262.0
3518.0,1298.0,2747.0
3526.0,1298.0,-5346.0
3683.0,1298.0,62.0
3785.0,1298.0,104.0
4017.0,1298.0,166.0
4147.0,1298.0,154.0
4236.0,1298.0,48.0
4698.0,1298.0,98.0
4748.0,1298.0,2673.0
4789.0,1298.0,114.0
4999.0,1298.0,278.0
5211.0,1298.0,182.0
5368.0,1298.0,60.0
5390.0,1298.0,98.0
5471.0,1298.0,122.0
2034.0,1299.0,267

713.0,1910.0,1.0
3532.0,1910.0,-1.0
670.0,1911.0,-1.0
696.0,1911.0,1.0
671.0,1912.0,-1.0
697.0,1912.0,1.0
670.0,1913.0,-1.0
3518.0,1913.0,-2.0
3526.0,1913.0,1.0
4097.0,1913.0,1.0
4493.0,1913.0,-1.0
671.0,1914.0,-1.0
3522.0,1914.0,-2.0
3530.0,1914.0,1.0
4098.0,1914.0,1.0
4499.0,1914.0,-1.0
696.0,1915.0,-1.0
1667.0,1915.0,1.0
3534.0,1915.0,1.0
4493.0,1915.0,-1.0
697.0,1916.0,-1.0
1668.0,1916.0,1.0
3537.0,1916.0,1.0
4499.0,1916.0,-1.0
699.0,1917.0,-1.0
1670.0,1917.0,1.0
3539.0,1917.0,1.0
4503.0,1917.0,-1.0
698.0,1918.0,-1.0
1669.0,1918.0,1.0
3538.0,1918.0,1.0
4501.0,1918.0,-1.0
1667.0,1919.0,-1.0
3526.0,1919.0,-1.0
4097.0,1919.0,1.0
1668.0,1920.0,-1.0
3530.0,1920.0,-1.0
4098.0,1920.0,1.0
1670.0,1921.0,-1.0
3532.0,1921.0,-1.0
4100.0,1921.0,1.0
1669.0,1922.0,-1.0
3531.0,1922.0,-1.0
4099.0,1922.0,1.0
1667.0,1923.0,-1.0
3526.0,1923.0,-1.0
4093.0,1923.0,1.0
1668.0,1924.0,-1.0
3530.0,1924.0,-1.0
4094.0,1924.0,1.0
1670.0,1925.0,-1.0
3532.0,1925.0,-1.0
4096.0,1925.0,1.0
1669.0,1926.0,-1.0
3531.0,

3107.0,2719.0,6.0
3521.0,2719.0,9.0
3529.0,2719.0,-9.0
4361.0,2719.0,-9.0
4367.0,2719.0,9.0
14.0,2720.0,-1.0
1994.0,2720.0,11.0
2645.0,2720.0,-10.0
3102.0,2720.0,-9.0
3107.0,2720.0,9.0
3521.0,2720.0,10.0
3529.0,2720.0,-10.0
4361.0,2720.0,-10.0
4367.0,2720.0,10.0
253.0,2721.0,-1.0
1994.0,2721.0,11.0
2645.0,2721.0,-10.0
3102.0,2721.0,-6.0
3107.0,2721.0,6.0
3521.0,2721.0,10.0
3529.0,2721.0,-10.0
4361.0,2721.0,-10.0
4367.0,2721.0,10.0
173.0,2722.0,-1.0
1994.0,2722.0,11.0
2645.0,2722.0,-10.0
3102.0,2722.0,-5.0
3107.0,2722.0,5.0
3521.0,2722.0,10.0
3529.0,2722.0,-10.0
4361.0,2722.0,-10.0
4367.0,2722.0,10.0
25.0,2723.0,-1.0
1994.0,2723.0,10.0
2645.0,2723.0,-9.0
3102.0,2723.0,-7.0
3107.0,2723.0,7.0
3521.0,2723.0,9.0
3529.0,2723.0,-9.0
4361.0,2723.0,-9.0
4367.0,2723.0,9.0
67.0,2724.0,-1.0
1994.0,2724.0,11.0
2645.0,2724.0,-10.0
3102.0,2724.0,-8.0
3107.0,2724.0,8.0
3521.0,2724.0,10.0
3529.0,2724.0,-10.0
4361.0,2724.0,-10.0
4367.0,2724.0,10.0
495.0,2725.0,-1.0
1994.0,2725.0,11.0
2645.0,2725.0,-10.0

5034.0,3424.0,-1.0
194.0,3425.0,-1.0
799.0,3425.0,1.0
2642.0,3425.0,1.0
5034.0,3425.0,-1.0
825.0,3426.0,1.0
2642.0,3426.0,1.0
3563.0,3426.0,-1.0
5034.0,3426.0,-1.0
822.0,3427.0,1.0
2642.0,3427.0,1.0
2920.0,3427.0,-1.0
5034.0,3427.0,-1.0
40.0,3428.0,-1.0
792.0,3428.0,1.0
2642.0,3428.0,1.0
5034.0,3428.0,-1.0
13.0,3429.0,-1.0
787.0,3429.0,1.0
2642.0,3429.0,1.0
5034.0,3429.0,-1.0
846.0,3430.0,1.0
2642.0,3430.0,1.0
5034.0,3430.0,-1.0
5311.0,3430.0,-1.0
845.0,3431.0,1.0
2642.0,3431.0,1.0
5034.0,3431.0,-1.0
5163.0,3431.0,-1.0
71.0,3432.0,-1.0
795.0,3432.0,1.0
2642.0,3432.0,1.0
5034.0,3432.0,-1.0
827.0,3433.0,1.0
2642.0,3433.0,1.0
3650.0,3433.0,-1.0
5034.0,3433.0,-1.0
828.0,3434.0,1.0
2642.0,3434.0,1.0
3655.0,3434.0,-1.0
5034.0,3434.0,-1.0
837.0,3435.0,1.0
2642.0,3435.0,1.0
4082.0,3435.0,-1.0
5034.0,3435.0,-1.0
216.0,3436.0,-1.0
803.0,3436.0,1.0
2642.0,3436.0,1.0
5034.0,3436.0,-1.0
270.0,3437.0,-1.0
810.0,3437.0,1.0
2642.0,3437.0,1.0
5034.0,3437.0,-1.0
200.0,3438.0,-1.0
798.0,3438.0,1.0
2642.0

3521.0,4192.0,-1.0
3529.0,4192.0,1.0
4373.0,4192.0,1.0
4380.0,4192.0,-1.0
4497.0,4192.0,-1.0
1230.0,4193.0,-1.0
1718.0,4193.0,1.0
3518.0,4193.0,-1.0
4360.0,4193.0,1.0
4366.0,4193.0,-1.0
1716.0,4194.0,1.0
1718.0,4194.0,-1.0
3518.0,4194.0,-1.0
3526.0,4194.0,1.0
4371.0,4194.0,1.0
4378.0,4194.0,-1.0
4493.0,4194.0,-1.0
1717.0,4195.0,1.0
1719.0,4195.0,-1.0
3521.0,4195.0,-1.0
3529.0,4195.0,1.0
4373.0,4195.0,1.0
4380.0,4195.0,-1.0
4497.0,4195.0,-1.0
1232.0,4196.0,-1.0
1719.0,4196.0,1.0
3521.0,4196.0,-1.0
4361.0,4196.0,1.0
4367.0,4196.0,-1.0
1232.0,4197.0,-1.0
1717.0,4197.0,1.0
3529.0,4197.0,-1.0
1701.0,4198.0,-1.0
1713.0,4198.0,1.0
3524.0,4198.0,-1.0
3532.0,4198.0,1.0
4376.0,4198.0,1.0
4383.0,4198.0,-1.0
4503.0,4198.0,-1.0
1711.0,4199.0,1.0
1713.0,4199.0,-1.0
3524.0,4199.0,-1.0
3532.0,4199.0,1.0
4376.0,4199.0,1.0
4383.0,4199.0,-1.0
4503.0,4199.0,-1.0
1225.0,4200.0,-1.0
1711.0,4200.0,1.0
3524.0,4200.0,-1.0
4376.0,4200.0,1.0
4383.0,4200.0,-1.0
1709.0,4201.0,1.0
1713.0,4201.0,-1.0
3524.0,4201.0,-

Excessive output truncated after 524288 bytes.

In [3]:
s= split(s,"\n")
index= 4
S= zeros(8404, 13094)
while !startswith(s[index],"vector") && !startswith(s[index],"matrix")
    t= split(s[index],',')
    i= convert(Int64, parse(Float64,t[1]))
    j= convert(Int64, parse(Float64,t[2]))
    S[i,j]= parse(Float64,t[3])
    index+=1
end
print(s[index],'\n')
index+=1
print(s[index])
index+=2

vector,row,col
u1,13094,1

55940

In [4]:
l= zeros(13094,1)
u= zeros(13094,1)
while !startswith(s[index],"vector") && !startswith(s[index],"matrix")
    t= split(s[index],',')
    i= convert(Int64, parse(Float64,t[1]))
    u[i]= parse(Float64,t[2])
    index+=1
end
index+=3
while index<=length(s)-1
    t= split(s[index],',')
    i= convert(Int64, parse(Float64,t[1]))
    l[i]= parse(Float64,t[2])
    index+=1
end

In [5]:
(m,n)=size(S)

(8404, 13094)

In [6]:
l1 = l
u1= u

13094×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.21494260516228897
 0.0
 9.128911564253195e-17
 0.754933344258207
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [7]:
mzeros = zeros(m,1)

8404×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [8]:
nones = ones(n,1)

13094×1 Array{Float64,2}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 ⋮
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
model = Model(GLPK.Optimizer)
@variable(model, l1[i] <= v[i = 1:n] <= u1[i])
@variable(model,w[1:n])
@constraint(model, S*v .== mzeros)
@constraint(model,w .>= v)
@constraint(model,w .>= -v)
@objective(model,Min,sum(nones[i]*w[i] for i in 1:n)) #
optimize!(model)
x= JuMP.value.(w)

13094-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  1.124906401398651e-16
  0.0
 -6.961629041525816e-17
  0.0
  0.0
  0.0
  0.0
  ⋮
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0

In [27]:
a= 1
function get_step(index_zeros,x)
    grad= [exp(-a*x[j]) for j in 1:n]
    model = Model(GLPK.Optimizer)
    @variable(model, l1[i] <= v[i = 1:n] <= u1[i])
    @variable(model,w[1:n])
    @constraint(model, S*v .== mzeros)
    @constraint(model,w .>= v)
    @constraint(model,w .>= -v)
    for i in index_zeros
        @constraint(model,w[i]==0)
    end
    @objective(model,Min,sum(grad[i]*w[i] for i=1:n))
    optimize!(model)
    if sum(grad.*JuMP.value.(w))>=sum(grad.*x)
        return -1, -1
    else    
        return JuMP.value.(w), JuMP.value.(v)
    end    
end 

get_step (generic function with 1 method)

In [28]:
num= 0
answer= []
for i in 1:10
    index_zeros= zeros(Int64 ,n,1)
    k=1
    for j in 1:n
        if x[j]==0
            index_zeros[k]= j
            k= k+1
        end
    end
    index_zeros= index_zeros[1:k-1]
    next_x, next_answer= get_step(index_zeros,x)
    if next_x[1]==-1
        break
    end
    x= next_x
    answer= next_answer
    num+=1
    print(num,'\n')
end    

1
2
3
4
5


In [29]:
function num_zeros(v)
    zero_num= 0
    for i in 1:n
        if abs(v[i])<=1e-10
            zero_num+=1
        end
    end
    return zero_num
end

num_zeros (generic function with 1 method)

In [31]:
#answer= JuMP.value.(v)
zero_num= num_zeros(answer)
must_be_zeros= zeros(Int64, zero_num+1, 1)
others= zeros(n-zero_num, 1)
k=1
ind= 1
for i in 1:n
    if abs(answer[i])<=1e-10
        must_be_zeros[k]= i
        k= k+1
    else
        others[ind]=i
        ind= ind+1
    end
end
print(others)

[1979.0; 1980.0; 2315.0; 2365.0; 2876.0; 4271.0; 4713.0; 4714.0; 5210.0; 5211.0; 5268.0; 5355.0; 5409.0; 5411.0; 5449.0; 5450.0; 5468.0; 5491.0; 5515.0; 5516.0; 5526.0; 5531.0; 5539.0; 5540.0; 5550.0; 5560.0; 5563.0; 5565.0; 5578.0; 5589.0; 5603.0; 5626.0; 5635.0; 5641.0; 5643.0; 5651.0; 5652.0; 5657.0; 5662.0; 5692.0; 5696.0; 5707.0; 5718.0; 5736.0; 5748.0; 5750.0; 5778.0; 5786.0; 5797.0; 5798.0; 5802.0; 5815.0; 5831.0; 5836.0; 5844.0; 5875.0; 5921.0; 5927.0; 5931.0; 5938.0; 5942.0; 5946.0; 5950.0; 5984.0; 5986.0; 5990.0; 5997.0; 6004.0; 6031.0; 6061.0; 6066.0; 6075.0; 6076.0; 6086.0; 6092.0; 6102.0; 6116.0; 6126.0; 6145.0; 6240.0; 6306.0; 6313.0; 6344.0; 6348.0; 6544.0; 6650.0; 8143.0; 8189.0; 8239.0; 8267.0; 8282.0; 9634.0; 9646.0; 9670.0; 9676.0; 9864.0; 9875.0; 9879.0; 9888.0; 10001.0; 11205.0; 11318.0; 11458.0; 11504.0; 11532.0; 11571.0; 12301.0; 12303.0; 12304.0; 12309.0]

In [32]:
using MathOptInterface
tedad= 0
for m in others
    must_be_zeros[length(must_be_zeros)]= convert(Int64, m)
    model = Model(GLPK.Optimizer)
    @variable(model, l1[i] <= v[i = 1:n] <= u1[i])
    @variable(model,w[1:n])
    @constraint(model, S*v .== mzeros)
    @constraint(model,w .>= v)
    @constraint(model,w .>= -v)
    for i in must_be_zeros
        @constraint(model,w[i]==0)
    end
    @objective(model,Min,sum(nones[i]*w[i] for i=1:n)) #
    optimize!(model)
    if termination_status(model)!=MathOptInterface.INFEASIBLE
        answer= JuMP.value.(v)
        print(m)
        break
    end 
    tedad+=1
    if tedad%10==0
        print(tedad)
    end    
end

105411.0

In [148]:
@show termination_status(model)
@show primal_status(model)
@show dual_status(model)
@show objective_value(model)
@show JuMP.value.(v)

termination_status(model) = MathOptInterface.OPTIMAL
primal_status(model) = MathOptInterface.FEASIBLE_POINT
dual_status(model) = MathOptInterface.FEASIBLE_POINT
objective_value(model) = 71.91033404910509
JuMP.value.(v) = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.304058203180764e-16, -0.17078248193164144, -6.961629041525816e-17, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0304187042958248, 0.0, 0.0, 9.619171167839755e-17, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -8.39

13094-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  5.304058203180764e-16
 -0.17078248193164144
 -6.961629041525816e-17
  0.0
  0.0
  0.0
  0.0
  ⋮
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0

In [150]:
print(num_zeros(JuMP.value.(v)))
using DelimitedFiles
open("output.txt","w") do io
    writedlm(io, JuMP.value.(v))
end

12813